export { default as Navbar } from './Navbar/page'
export { default as HeaderTop } from './HeaderTop/page'
export { default as SearchBar } from './SearchBar/page'
export { default as Header } from './Header/page'
export { default as PostS } from './Post/page.jsx'
export { default as Sidebar } from './Sidebar/page'
export { default as Footer } from './Footer/page'